language: php

php:
  - 5.5

env:
  - DB=mysql

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS baasify;" -uroot; fi
  - mv .env.example .env
  - composer update

script: phpunit --configuration phpunit_$DB.xml --coverage-text
